# Generated by Django 5.1.4 on 2024-12-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_rooms_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
